### ISSUE TITLE
clase 2

### ISSUE THREAD

**Issue by nestdanchia** [EscuelaIt/redux-angular#1]
hola mi nombre es Nestor
codifique la clase 2 como tarea ( no la encontre en el repo) y funciona pero al reiniciar porque modifico el codigo en el vsc
primero da esto pere igual se renderiza ok
1.FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
pero luego al reiniar nuevamente no renderiza y da este error
2.ERROR in Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at AngularCompilerPlugin._updateForkedTypeChecker (C:\AAAAAABBBBLIBROREACTIVEREACT\Capitulo3\cap-tres\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:370:34)
    at Promise.resolve.then (C:\AAAAAABBBBLIBROREACTIVEREACT\Capitulo3\cap-tres\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:208:22)
    at process._tickCallback (internal/process/next_tick.js:103:7)
USO VSC con un w10 4gigas ram

**Comment by nicobytes** [comment]
@nestdanchia mira aqui puedes encontrar el repo https://github.com/EscuelaIt/redux-angular-counter-app

**Comment by nestdanchia** [comment]
Con tu proyecto da el mismo error  mi configuracion es 
VSC 
Angular CLI: 1.5.0
Node: 6.10.0
OS: win32 ia32
testie otro proyecto de angular sin redux!!  una aplicacion que se comunica con firebase y no se enloquese nunca gracias

**Comment by nestdanchia** [comment]
Nicolas como te comente es un error de mi configuracion  que ocurre con ngrx  porque ejecute el codigo de ng-book 2 a chat app using RxJS  no usan ngrx y cualquier codigo de Angular que no tenga ngrx no me da error .Busque por todos lados y encontre pedidos de auxilio sobre esta cuestion pero ninguna respuesta por ejemplo en el siguiente link https://github.com/angular/angular-cli/issues/8331

**Comment by nicobytes** [comment]
@nestdanchia que dependecias estas usando o es decir yo he usado ngrx + firebase y me funciona perfectamente, cual estas usando tu en tu proyecto?

**Comment by nestdanchia** [comment]
Nicolas encontre porque daba error era que tenia globalmente angular-cli
1.5.2 y el proyecto es con angular-cli 1.5.0 entiendo que no deberia ser
asi porque por  el digito de cambio son menores los cambios pero asi lo
fue  gracias

2017-11-16 14:36 GMT-03:00 Nicolas Molina Monroy <notifications@github.com>:

**Comment by Adricz22** [comment]
Hello @EscuelaIt 👋

# 🌍 Top International Developer Events

Discover the **most influential tech conferences and developer events** happening around the world.  
Connect, learn, and grow with the **global developer community**.

---

## 🚀 Why Join?
- 🔴 **Live Events** – Stay updated with the latest happenings in tech  
- 🌐 **Global Community** – Network with developers from all continents  
- 📅 **Updated Daily** – Fresh events, always current  
- 🏆 **Top 10 Developer Events** – Hand-picked to shape the future of technology  

From **cutting-edge frameworks** to **emerging paradigms**, we bring you the opportunities that matter.

---

## 🔑 Get Started  
**[➡️ Continue with GitHub](https://www.globaldevsummit.com/)**  
🔒 **Connect securely** • Save favorites • Get personalized recommendations  

---

## 📌 Highlights
- Meet industry leaders and tech innovators  
- Join exclusive technical workshops  
- Explore new frameworks, tools, and best practices  
- Grow your personal and professional network  

---

> 📢 **Tip:** Bookmark the page and check daily for new opportunities.  
Your next big career move could start here!

---
